In [1]:
from pandas import Series, DataFrame
import pandas as pd

data = {'첫번째': [1,2], '두번째': [3,4]}
df = DataFrame(data=data)

df

   첫번째  두번째
0    1    3
1    2    4

In [2]:
data = [[10, 20], [30, 40]]
myIndex = ["row1", "row2"]
myColumn = ["col1", "col2"]

df = DataFrame(data=data, index=myIndex, columns=myColumn)

type(df)

pandas.DataFrame

In [3]:
df

      col1  col2
row1    10    20
row2    30    40

In [5]:
from pandas import DataFrame
import pandas as pd

# 첫번째 데이터 프레임.
data = {
    "종가":[633300, 63822],
    "거래량":[2365845, 45755415]
}
index = ["2026-07-01","2026-07-02"]
df1 = DataFrame(data=data, index=index)

# 두번째 데이터 프레임
data = {
    "종가": [60800,60200],
    "거래량": [25235122,12548585]
}
index = ["2026-07-03", "2026-07-04"]
df2 = DataFrame(data=data, index=index)

df1
df2

               종가       거래량
2026-07-03  60800  25235122
2026-07-04  60200  12548585

In [7]:
pd.concat([df1, df2])

                종가       거래량
2026-07-01  633300   2365845
2026-07-02   63822  45755415
2026-07-03   60800  25235122
2026-07-04   60200  12548585