In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

df= DataFrame(
    {
        "key1": ["a","a","b","b","a","a","a","b","b","a"],
        "key2": ["one","two","one","two","one","one","two","one","two","one"],
        "col1": np.random.randn(10),
        "col2": np.random.randn(10)
    }
)

df

  key1 key2      col1      col2
0    a  one -0.481925  0.614061
1    a  two -1.075845  2.049038
2    b  one -0.612952 -1.585861
3    b  two  0.668328 -0.871204
4    a  one -1.410730  1.503201
5    a  one -0.811669  1.817800
6    a  two -0.219334  1.209997
7    b  one -0.524751 -0.149037
8    b  two -0.035681  1.566326
9    a  one  0.422521 -1.490115

In [3]:
grouped = df.groupby("key1")["col1"]
grouped

In [4]:
# 이 grouped 변수는 pandas 패키지의 SeriesGroupBy 객체임.
# col1을 슬라이싱해서 Series 객체로 받아서 집계를 한 결과물임.
# 이 객체는 그룹 연산을 위해 필요한 모든 정보를 가지고 있기 때문에 각 그룹에 어떤 연산을 적용할 수 있음.

In [5]:
# 평균값을 구하려면 mean() 메서드를 사용하면 됨. 합계를 구할 경우 sum(), 개수를 보고 싶은 경우에는 count() 를 호출하면 됨.
print(grouped.mean())
print(grouped.sum())
print(grouped.count())

key1
a   -0.596164
b   -0.126264
Name: col1, dtype: float64
key1
a   -3.576983
b   -0.505056
Name: col1, dtype: float64
key1
a    6
b    4
Name: col1, dtype: int64

In [6]:
# 이번에는 학급 성적표를 사용해서 각 그룹별 통계를 작성하는 것을 연습해 봄.
# 학급 성적.
dfClass = DataFrame(
    {
        "학급": [1, 1, 2, 2, 1],
        "이름": ["홍길동", "전우치", "이순신", "박문수", "김길동"],
        "국어": [100, 90, 95, 100, 80],
        "영어": [80, 90, 95, 92, 89],
        "수학": [90, 80, 92, 100, 90]
    }
)

dfClass

   학급   이름   국어  영어   수학
0   1  홍길동  100  80   90
1   1  전우치   90  90   80
2   2  이순신   95  95   92
3   2  박문수  100  92  100
4   1  김길동   80  89   90

In [7]:
# 아래와 같이 특정 과목을 슬라이싱 할 수 있음.
dfClass["수학"]

0     90
1     80
2     92
3    100
4     90
Name: 수학, dtype: int64

In [ ]:
# 파이썬 전역 함수 sum() 을 사용해서 국어 과목의 합계를 계산할 수 있음.
sum(dfClass["국어"])

465

In [10]:
# 아래와 같이 오름차순으로 정렬할 수 있음. 국어 성적으로 정렬해 봄.
dfClass.sort_values("국어")

   학급   이름   국어  영어   수학
4   1  김길동   80  89   90
1   1  전우치   90  90   80
2   2  이순신   95  95   92
0   1  홍길동  100  80   90
3   2  박문수  100  92  100

In [11]:
#평균을 구할 경우에도 아래와 같이 작업하면 됨.
sum(dfClass["국어"])/5

93.0

In [14]:
# 약순(내림차순)으로 정렬하는 경우는 아래와 같이 함.
dfClass.sort_values("국어", ascending=False)

   학급   이름   국어  영어   수학
0   1  홍길동  100  80   90
3   2  박문수  100  92  100
2   2  이순신   95  95   92
1   1  전우치   90  90   80
4   1  김길동   80  89   90

In [15]:
# 각 학생별로 국어 + 영어 + 수학 점수를 합계를 낸 값을 "총점"이라는 컬럼으로 추가할 수 있음.
# 기존에 없는 컬럼명을 주면 바로 추가됨.
dfClass["총점"]= dfClass["국어"] + dfClass["영어"] + dfClass["수학"]

In [16]:
dfClass

   학급   이름   국어  영어   수학   총점
0   1  홍길동  100  80   90  270
1   1  전우치   90  90   80  260
2   2  이순신   95  95   92  282
3   2  박문수  100  92  100  292
4   1  김길동   80  89   90  259

In [17]:
dfClass["평균"] = (dfClass["국어"] + dfClass["영어"] + dfClass["국어"]) /3

In [18]:
dfClass

   학급   이름   국어  영어   수학   총점         평균
0   1  홍길동  100  80   90  270  93.333333
1   1  전우치   90  90   80  260  90.000000
2   2  이순신   95  95   92  282  95.000000
3   2  박문수  100  92  100  292  97.333333
4   1  김길동   80  89   90  259  83.000000

In [20]:
# 이렇게 생성된 결과에 평균 컬럼을 기준으로 내림차순 으로 다시 정렬해 봄.
dfClass.sort_values("평균", ascending=False)

   학급   이름   국어  영어   수학   총점         평균
3   2  박문수  100  92  100  292  97.333333
2   2  이순신   95  95   92  282  95.000000
0   1  홍길동  100  80   90  270  93.333333
1   1  전우치   90  90   80  260  90.000000
4   1  김길동   80  89   90  259  83.000000

In [21]:
# 이렇게 정리한 DataFrame 에서 학급을 기준으로 그룹을 만들 수 있음.
# groupby 메서드예 "학급"을 지정하고 "국어" 컬럼의 평균을 생성.
dfClass.groupby("학급")["국어"].mean()

학급
1    90.0
2    97.5
Name: 국어, dtype: float64

In [22]:
#DataFrame에서 agg() 를 사용하면 "변수명", "통계"할 내용을 지정할 수 있음.
# 학급별로 그룹을 만들고,"수학" 컬럼의 평균을 구하는 코드임.
# groupby() 를 사용해서 전체를 집계하는 것이 아닌, 그룹별 집계가 필요한 agg() - aggregate 집계를 사용할수 있음.
dfClass.groupby("학급").agg(수학평균=("수학","mean"))

         수학평균
학급
1   86.666667
2   96.000000

In [23]:
# 출력되는 수학평균이 실수 부분을 2자리 까지만 출력되도록 하려면 아래와 같이 작업함.
dfClass.groupby("학급").agg(수학평균=("수학", lambda x: round(x.mean(), 2)))

     수학평균
학급
1   86.67
2   96.00

In [24]:
# 마지막으로 학급별로 그룹을 생성해서 국어, 수학, 영어에 대한 평균 점수를 구해 봄.
# mean 는 평균값을 의미함. count 는 실제 포함된 갯수를 의미함. 
dfClass.groupby("학급").agg(
    국어평균 = ("국어", "mean"),
    수학평균 = ("수학", lambda x: round(x.mean(),2)),
    영어평균 = ("영어", lambda x: round(x.mean(),2)),
    갯수 = ("학급", "count") 
)

    국어평균   수학평균   영어평균  갯수
학급
1   90.0  86.67  86.33   3
2   97.5  96.00  93.50   2