In [2]:
from pandas import DataFrame
import pandas as pd

# 첫번째 데이터프레임.
data = [
    ["컴퓨터와 주변기기", "044330", "주연테크", 380],
    ["교육서비스", "072870", "메카스터디",11320],
    ["컴퓨터와 주변기기", "129890", '앱코', 1227]
]

columns = ["업종","품목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns=columns)

# 두번째 데이터프레임
data = [
    ["건설", 0.05],
    ["자동차", 0.93],
    ["교육서비스", 0.82],
    ["컴퓨터와 주변기기", 0.11]
]

columns = ["업종", "등락률"]
df2 = DataFrame(data=data, columns=columns)

print(df1)
print(df2)

          업종    품목코드    종목명    현재가
0  컴퓨터와 주변기기  044330   주연테크    380
1      교육서비스  072870  메카스터디  11320
2  컴퓨터와 주변기기  129890     앱코   1227
          업종   등락률
0         건설  0.05
1        자동차  0.93
2      교육서비스  0.82
3  컴퓨터와 주변기기  0.11

In [3]:
df = pd.merge(left=df1, right=df2, on="업종")
df

          업종    품목코드    종목명    현재가   등락률
0  컴퓨터와 주변기기  044330   주연테크    380  0.11
1      교육서비스  072870  메카스터디  11320  0.82
2  컴퓨터와 주변기기  129890     앱코   1227  0.11

In [4]:
df_left = pd.merge(left=df1, right=df2, how='left', on='업종')
df_left

          업종    품목코드    종목명    현재가   등락률
0  컴퓨터와 주변기기  044330   주연테크    380  0.11
1      교육서비스  072870  메카스터디  11320  0.82
2  컴퓨터와 주변기기  129890     앱코   1227  0.11

In [5]:
df_right = pd.merge(left=df1, right=df2, how='right', on='업종')
df_right

          업종    품목코드    종목명      현재가   등락률
0         건설     NaN    NaN      NaN  0.05
1        자동차     NaN    NaN      NaN  0.93
2      교육서비스  072870  메카스터디  11320.0  0.82
3  컴퓨터와 주변기기  044330   주연테크    380.0  0.11
4  컴퓨터와 주변기기  129890     앱코   1227.0  0.11

In [6]:
df_outer = pd.merge(left=df1, right=df2, how='outer', on='업종')
df_outer

          업종    품목코드    종목명      현재가   등락률
0         건설     NaN    NaN      NaN  0.05
1      교육서비스  072870  메카스터디  11320.0  0.82
2        자동차     NaN    NaN      NaN  0.93
3  컴퓨터와 주변기기  044330   주연테크    380.0  0.11
4  컴퓨터와 주변기기  129890     앱코   1227.0  0.11

In [8]:
# 첫번째 데이터프레임.
data = [
    ["컴퓨터와주변기기","044290","주연테크", 380],
    ["교육서비스", "072890","메가스터디",11320],
    ["식품", "017810","풀무원", 11460]
]
columns = ["업종", "품목코드", "종목명", "현재가"]
df1 = DataFrame(data=data, columns = columns)

# 두번째 데이터프레임.
data = [
    ["건설", 0.05],
    ["자동차", 0.93],
    ["교육서비스",0.82],
    ["컴퓨터와주변기기", 0.11]
]
columns = ["업종명칭", "등락율"]
df2 = DataFrame(data=data, columns= columns)

df = pd.merge(left=df1, right=df2, left_on="업종", right_on="업종명칭")
df

         업종    품목코드    종목명    현재가      업종명칭   등락율
0  컴퓨터와주변기기  044290   주연테크    380  컴퓨터와주변기기  0.11
1     교육서비스  072890  메가스터디  11320     교육서비스  0.82